; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
; Non-commercial use only

#define MyAppName "DBConnector"
#define MyAppVersion "4.0"
#define MyAppPublisher "YazilimTurkiye"
#define MyAppURL "https://www.yazilimturkiye.com/"
#define MyAppExeName "DBConnector.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{2AC19E56-8563-445B-BBC9-AD8C810AF1E2}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppVerName={#MyAppName}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppPublisher}\{#MyAppName}
DisableDirPage=no
UninstallDisplayIcon={app}\{#MyAppExeName}
; "ArchitecturesAllowed=x64compatible" specifies that Setup cannot run
; on anything but x64 and Windows 11 on Arm.
ArchitecturesAllowed=x64compatible
; "ArchitecturesInstallIn64BitMode=x64compatible" requests that the
; install be done in "64-bit mode" on x64 or Windows 11 on Arm,
; meaning it should use the native 64-bit Program Files directory and
; the 64-bit view of the registry.
ArchitecturesInstallIn64BitMode=x64compatible
DefaultGroupName={#MyAppName}
AllowNoIcons=yes
; Uncomment the following line to run in non administrative install mode (install for current user only).
;PrivilegesRequired=lowest
OutputDir=C:\Users\HOME-PC\Documents\GitHub\DBConnector\Install for Windows
OutputBaseFilename=DBConnector_Setup_v4.0
SetupIconFile=C:\Users\HOME-PC\Documents\GitHub\DBConnector\DBConnector\logo.ico
SolidCompression=yes
WizardStyle=modern dynamic

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "turkish"; MessagesFile: "compiler:Languages\Turkish.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "C:\Users\HOME-PC\Documents\GitHub\DBConnector\DBConnector\bin\Release\net9.0-windows10.0.22000.0\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\HOME-PC\Documents\GitHub\DBConnector\DBConnector\bin\Release\net9.0-windows10.0.22000.0\Azure.Core.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\HOME-PC\Documents\GitHub\DBConnector\DBConnector\bin\Release\net9.0-windows10.0.22000.0\Azure.Identity.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\HOME-PC\Documents\GitHub\DBConnector\DBConnector\bin\Release\net9.0-windows10.0.22000.0\BouncyCastle.Cryptography.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\HOME-PC\Documents\GitHub\DBConnector\DBConnector\bin\Release\net9.0-windows10.0.22000.0\DBConnector.deps.json"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\HOME-PC\Documents\GitHub\DBConnector\DBConnector\bin\Release\net9.0-windows10.0.22000.0\DBConnector.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\HOME-PC\Documents\GitHub\DBConnector\DBConnector\bin\Release\net9.0-windows10.0.22000.0\DBConnector.dll.config"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\HOME-PC\Documents\GitHub\DBConnector\DBConnector\bin\Release\net9.0-windows10.0.22000.0\DBConnector.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\HOME-PC\Documents\GitHub\DBConnector\DBConnector\bin\Release\net9.0-windows10.0.22000.0\DBConnector.pdb"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\HOME-PC\Documents\GitHub\DBConnector\DBConnector\bin\Release\net9.0-windows10.0.22000.0\DBConnector.runtimeconfig.json"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\HOME-PC\Documents\GitHub\DBConnector\DBConnector\bin\Release\net9.0-windows10.0.22000.0\Google.Protobuf.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\HOME-PC\Documents\GitHub\DBConnector\DBConnector\bin\Release\net9.0-windows10.0.22000.0\K4os.Compression.LZ4.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\HOME-PC\Documents\GitHub\DBConnector\DBConnector\bin\Release\net9.0-windows10.0.22000.0\K4os.Compression.LZ4.Streams.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\HOME-PC\Documents\GitHub\DBConnector\DBConnector\bin\Release\net9.0-windows10.0.22000.0\K4os.Hash.xxHash.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\HOME-PC\Documents\GitHub\DBConnector\DBConnector\bin\Release\net9.0-windows10.0.22000.0\Microsoft.Bcl.AsyncInterfaces.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\HOME-PC\Documents\GitHub\DBConnector\DBConnector\bin\Release\net9.0-windows10.0.22000.0\Microsoft.Bcl.Cryptography.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\HOME-PC\Documents\GitHub\DBConnector\DBConnector\bin\Release\net9.0-windows10.0.22000.0\Microsoft.Data.SqlClient.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\HOME-PC\Documents\GitHub\DBConnector\DBConnector\bin\Release\net9.0-windows10.0.22000.0\Microsoft.Extensions.Caching.Abstractions.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\HOME-PC\Documents\GitHub\DBConnector\DBConnector\bin\Release\net9.0-windows10.0.22000.0\Microsoft.Extensions.Caching.Memory.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\HOME-PC\Documents\GitHub\DBConnector\DBConnector\bin\Release\net9.0-windows10.0.22000.0\Microsoft.Extensions.DependencyInjection.Abstractions.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\HOME-PC\Documents\GitHub\DBConnector\DBConnector\bin\Release\net9.0-windows10.0.22000.0\Microsoft.Extensions.Logging.Abstractions.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\HOME-PC\Documents\GitHub\DBConnector\DBConnector\bin\Release\net9.0-windows10.0.22000.0\Microsoft.Extensions.Options.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\HOME-PC\Documents\GitHub\DBConnector\DBConnector\bin\Release\net9.0-windows10.0.22000.0\Microsoft.Extensions.Primitives.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\HOME-PC\Documents\GitHub\DBConnector\DBConnector\bin\Release\net9.0-windows10.0.22000.0\Microsoft.Identity.Client.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\HOME-PC\Documents\GitHub\DBConnector\DBConnector\bin\Release\net9.0-windows10.0.22000.0\Microsoft.Identity.Client.Extensions.Msal.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\HOME-PC\Documents\GitHub\DBConnector\DBConnector\bin\Release\net9.0-windows10.0.22000.0\Microsoft.IdentityModel.Abstractions.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\HOME-PC\Documents\GitHub\DBConnector\DBConnector\bin\Release\net9.0-windows10.0.22000.0\Microsoft.IdentityModel.JsonWebTokens.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\HOME-PC\Documents\GitHub\DBConnector\DBConnector\bin\Release\net9.0-windows10.0.22000.0\Microsoft.IdentityModel.Logging.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\HOME-PC\Documents\GitHub\DBConnector\DBConnector\bin\Release\net9.0-windows10.0.22000.0\Microsoft.IdentityModel.Protocols.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\HOME-PC\Documents\GitHub\DBConnector\DBConnector\bin\Release\net9.0-windows10.0.22000.0\Microsoft.IdentityModel.Protocols.OpenIdConnect.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\HOME-PC\Documents\GitHub\DBConnector\DBConnector\bin\Release\net9.0-windows10.0.22000.0\Microsoft.IdentityModel.Tokens.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\HOME-PC\Documents\GitHub\DBConnector\DBConnector\bin\Release\net9.0-windows10.0.22000.0\Microsoft.SqlServer.Server.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\HOME-PC\Documents\GitHub\DBConnector\DBConnector\bin\Release\net9.0-windows10.0.22000.0\Microsoft.Windows.SDK.NET.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\HOME-PC\Documents\GitHub\DBConnector\DBConnector\bin\Release\net9.0-windows10.0.22000.0\MySql.Data.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\HOME-PC\Documents\GitHub\DBConnector\DBConnector\bin\Release\net9.0-windows10.0.22000.0\MySqlConnector.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\HOME-PC\Documents\GitHub\DBConnector\DBConnector\bin\Release\net9.0-windows10.0.22000.0\Npgsql.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\HOME-PC\Documents\GitHub\DBConnector\DBConnector\bin\Release\net9.0-windows10.0.22000.0\Oracle.ManagedDataAccess.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\HOME-PC\Documents\GitHub\DBConnector\DBConnector\bin\Release\net9.0-windows10.0.22000.0\System.ClientModel.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\HOME-PC\Documents\GitHub\DBConnector\DBConnector\bin\Release\net9.0-windows10.0.22000.0\System.ComponentModel.Composition.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\HOME-PC\Documents\GitHub\DBConnector\DBConnector\bin\Release\net9.0-windows10.0.22000.0\System.DirectoryServices.Protocols.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\HOME-PC\Documents\GitHub\DBConnector\DBConnector\bin\Release\net9.0-windows10.0.22000.0\System.IdentityModel.Tokens.Jwt.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\HOME-PC\Documents\GitHub\DBConnector\DBConnector\bin\Release\net9.0-windows10.0.22000.0\System.Management.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\HOME-PC\Documents\GitHub\DBConnector\DBConnector\bin\Release\net9.0-windows10.0.22000.0\System.Memory.Data.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\HOME-PC\Documents\GitHub\DBConnector\DBConnector\bin\Release\net9.0-windows10.0.22000.0\WinRT.Runtime.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\HOME-PC\Documents\GitHub\DBConnector\DBConnector\bin\Release\net9.0-windows10.0.22000.0\ZstdSharp.dll"; DestDir: "{app}"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

